# This is a Nixpacks configuration file (nixpacks.toml)

# Providers: Specify the language/framework providers Nixpacks should use.
# In this case, it explicitly tells Nixpacks to use the "nodejs" provider.
# The "..." syntax can be used to include auto-detected providers alongside specific ones.
providers = ["nodejs"]

# Build: Configure the build process.
[build]
# nixPkgs: A list of Nix packages to install in the build environment.
# Here a specific version of Node.js and NPM are specified.
# Ensure these versions are supported by Nixpacks and NixOS.
nixPkgs = ['nodejs-18_x', 'npm-9_x']

# Start: Configure the command to start your application after the build.
[start]
# cmd: The command to execute to start your application.
# Make sure the path and command are correct for your project structure.
cmd = "cd signaling_server && node server.js"

# Variables: Define environment variables for your application's runtime.
[variables]
# PORT: The port your application should listen on. 
# This variable might be used by your application to listen on the specified port.
PORT = "3000"
# NODE_ENV: Set the Node.js environment to production for optimized builds.
NODE_ENV = "production"
