[build]
builder = "NIXPACKS"
buildCommand = "cd signaling_server && npm install"

[deploy]
startCommand = "cd signaling_server && node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables
[env]
PORT = "3000"
NODE_ENV = "production"
